behaviors:
  CheckersAI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    self_play:
      play_against_latest_model: true
      team_change: 0.5
      swap_steps: 5000
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
